name: Check Secrets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Vars and Secrets
        run: echo ${{vars.GREET}} ${{ vars.EMAIL_TOPIC }}
